language: node_js
sudo: required
node_js: 10
install:
  - npm install
  - npm install coveralls -g
script: 'npm run coverage'
before_script:
  - 'sudo chown root /opt/google/chrome/chrome-sandbox'
  - 'sudo chmod 4755 /opt/google/chrome/chrome-sandbox'
